### ISSUE TITLE
Provide daily quantitative feedback about number of contacts

### ISSUE THREAD

**Issue by stefferber** [corona-warn-app/cwa-wishlist#64] opened 2020-06-25 12:25 UTC
The app users are already convinced and probably the best ambassadors for additional active users. However today, the app does not provide data to promote it to additional users. Therefore, I think providing daily data about the app population in my environment would be helpful:

- How many Bluetooth devices did I "meet" today?
- How many of these are using the corona app?

## Problem and motivation
I think this will also help to get users more engaged daily and talk about it. It would also open up additional gamification features.

## Is this something you're interested in working on
Yes

**Comment by jkoepcke** [comment] 2020-06-25 12:33
This would also be nice to see that the app actually works at all. Especially in combination with the frequent region change warnings on iOS, it's unclear if it's working correctly.

**Comment by tens0rfl0w** [comment] 2020-06-25 14:19
Duplicate of #5.

Please keep in mind that such feature is not possible to implement, because the framework does not give any information about collected ids.

**Comment by ironjan** [comment] 2020-06-25 18:12
@tkowark See @tens0rfl0w 's comment above.

**Comment by tkowark** [comment] 2020-06-25 18:48
Thanks again, ironjan :-)

@stefferber we‘ll close this in favour of #5 and invite you to upvote the other issue.

**Closed by tkowark** 2020-06-25 18:48 UTC
Labels: feature request
