### ISSUE TITLE
iOS 14 CWA Home screen Widget

### ISSUE THREAD

**Issue by Bohne9** [corona-warn-app/cwa-wishlist#31] opened 2020-06-23 12:06 UTC
Here is just a quick idea how the CWA could use the new home screen widgets coming with iOS 14.

<img src="https://user-images.githubusercontent.com/24317813/85401449-4eaf0b00-b55a-11ea-9243-871aa7d2b4df.png" width=300px />

**Comment by niclasreich** [comment] 2020-06-23 12:42
Duplicate of #26 

#closerequest

**Comment by tkowark** [comment] 2020-06-25 18:52
Yes, we‘ll close that. But would be great if you could add the mockup to #26, @Bohne9 ?

**Closed by tkowark** 2020-06-25 18:52 UTC
Labels: feature request
