### ISSUE TITLE
Location QR Codes

### ISSUE THREAD

**Issue by martin-krueger** [corona-warn-app/cwa-wishlist#207] opened 2020-10-18 15:24 UTC
## Feature description

Every location where you have to record your address, e.g. restaurants, should also provide a QR code. The QR code can be scanned by the corona app. If another visitor enters a positive test result in the CWA, all other visitors of the location are also notified.

## Problem and motivation

1. CWA can be used by more mobile phones also be the ones which does not support the needed Blutooth technology.
2. Public health office are supported to track chains of infections.

## Is this something you're interested in working on

No

**Comment by Ein-Tim** [comment] 2020-10-18 15:45
Duplicate of #138

**Closed** 2020-10-18 16:10 UTC
Labels: feature request
