### ISSUE TITLE
Track missing test results

### ISSUE THREAD

**Issue by kno10** [corona-warn-app/cwa-wishlist#303] opened 2020-12-30 22:03 UTC
If a test result is not available after 7 days (21 is too large), the app should:

* instruct the user to try other means to access the result
* collect statistics of such cases to detect if there are data transfer issues with some labs
* ask the user to *voluntarily* provide additional information (rescan the QR code, enter the lab information that is supposed to process the sample, test date, etc.)

If the code is accepted by the corona warn app, it should **work eventually, not time out**.

The current situation (timeout after 21 days if there is some issue between lab and the corona warn app server) is completely unacceptable for users. They can*not* rely on the app to have their test result.

**Comment by Ein-Tim** [comment] 2020-12-30 22:22
Related Issues:

- #299
- #270

**Comment by heinezen** [comment] 2021-01-05 13:57
Hey @kno10 ,

Thank you for the suggestions. Because your feedback is very similar to the feature request raised in https://github.com/corona-warn-app/cwa-wishlist/issues/270 we will close this issue as a duplicate to keep the discussion in one place. However, your feedback is not lost and we have added your remarks to the corresponding Jira ticket (EXPOSUREAPP-3953). We will notify everyone in https://github.com/corona-warn-app/cwa-wishlist/issues/270 if we get any news about the progress on this feature request.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-01-05 13:57
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/270

**Closed** 2021-01-05 13:57 UTC
Labels: feature request
