### ISSUE TITLE
Get local regulation information on the basis of smartphone local data

### ISSUE THREAD

**Issue by alexanderkeller** [corona-warn-app/cwa-wishlist#253] opened 2020-11-04 18:14 UTC
## Current Implementation
Nothing similar found

## Suggested Enhancement
Up-to-date one must depending upon "Bundesland" on the appropriate Website of the "Bundesland" around there the accordingly valid regulations to see to be able. e.g. https://corona.saarland.de/DE/service/massnahmen/verordnung-stand-2020-10-30.html Users of the Corona Warn App are apparently willing to run a certain tracking through their smartphone anyway. Therefore it would be obvious in my opinion that the app automatically pulls the appropriate information from the corresponding website based on the location of the cell phone. 

Technically, this could be a cheap key/value list, which simply links to the corresponding website with the content of the regulation per state (key) 1-16. 
The country borders should be findable with LatLng data. For example, there is a website which apparently already uses this geo data to draw the border in the google map: https://www.bernhard-gaul.de/wissen/bundeslaender-gmaps.php

The list can be static from my point of view and it doesn't have to be over engineered, because probably a 17 state will not be added that fast and the links to the regulations seem to be quite stable to me. 

MVP1 on could simply be a link to the corresponding website. Something like 
"Rules currently valid for your current location **see here** ->"
MVP2 could then also crawl the content of the website with the regulation and then display it directly in the app. 

## Expected Benefits
I think the users are happy to see a tangible, simple new feature every now and then. I think this would also increase the acceptance for the high development costs if the app does not look the same since the release and nothing new is added. For the non computer scientist user, the only thing that remains is that 9 million has been spent by tax money on an app with three buttons

**Comment by MikeMcC399** [comment] 2020-11-04 18:41
@alexanderkeller 
Unfortunately you have duplicated your own submission in https://github.com/corona-warn-app/cwa-wishlist/issues/252.
So I suggest closing this one.

**Comment by dsarkar** [comment] 2020-11-05 08:57
Dear @alexanderkeller,

Thank you very much for your suggestion and posting. I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/151. I would like to ask you to continue any further discussion on that issue there.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-05 08:59
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/151

**Closed** 2020-11-05 09:00 UTC
Labels: duplicate, enhancement

**Comment by alexanderkeller** [comment] 2020-11-05 12:28
@MikeMcC399 Sorry I had internet connection problems yesterday and first submit #252 of my request was shown as error in GitHub. Sorry for the mistake. 

@dsarkar Sorry don´t find #151 because title was in german. Cool to see the progress in issue 151.
