### ISSUE TITLE
Generation of anonymous tracker string for records in restaurants and events

### ISSUE THREAD

**Issue by KarstenB** [corona-warn-app/cwa-wishlist#226] opened 2020-10-23 06:27 UTC
## Feature description

Allow the app to generate a short but unique string that can be written into the contact tracing books of restaurants or events, instead of your real identity.

## Problem and motivation
While I do like going to restaurants, I really hate the idea of writing down my full-address and contact phone number into a openly readable book. As it has shown that this book is also mis-used by the police and stalkers.

So if the app could generate a unique string that I could write into those books, instead of all my personal details, it would make the app more useful and potentially help the spread of the app.

Technically under the hood the app could treat the restaurant or event like a patient.

## Is this something you're interested in working on

Yes

**Comment by tobiashage** [comment] 2020-10-23 09:18
Duplicate of #208 and very similar to #138, #70 & #59. 

Discussion is currently continuing in #138

**Comment by MKCOOL142** [comment] 2020-10-24 16:15
And i thought I was unique when I wrote them a email about that exact same Idea I had 10 minutes ago haha, I hope they can manage to realize a system like that, but since I don't know how the existing infrastructure works it might be a bit harder to implement

**Comment by heinezen** [comment] 2020-10-25 17:39
Hey @KarstenB and @MKCOOL142 

Thanks for the input. This request is already discussed in https://github.com/corona-warn-app/cwa-wishlist/issues/138 as mentioned by @tobiashage . It is a very popular request from the community, so it is regularly discussed with the development team. Please subscribe to #138 if you want further updates on the progress of the feature request.

I will close this issue to keep the discussion centralized.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Closed** 2021-01-19 13:31 UTC
Labels: feature request
