### ISSUE TITLE
Exposure Update every Day not every 24h

### ISSUE THREAD

**Issue by wienans** [corona-warn-app/cwa-wishlist#133] opened 2020-07-28 10:48 UTC
Hey,
As an iOS user I was kindly asked to open the App every day to get an exposure update. 
But the app only updates the exposure if I open the app 24h after the last update. 

This is a bit annoying, because from day to day the update time propagates within the day.
e.g. first day 7:00 am updates
next day I have to wait until 7:01am to update, maybe I forget it and do it at 8:00 am and next day i have to wait until 8:01am and so on. 

My suggestion would be to update once a day and reset the update timer at 0:00 am. Than you can update the exposure any time a day and don’t effect the next days update time.

Greets, Sven

---
Internal Tracking ID: EXPOSUREAPP-1943, EXPOSUREAPP-2039

**Comment by tkowark** [comment] 2020-07-28 13:56
Thanks for your proposal. Since that functionality would be nice to have for both apps, we moved the issue to the wishlist repository.

**Comment by MichaelPFrey** [comment] 2020-08-01 08:23
> My suggestion would be to update once a day and reset the update timer at 0:00 am. Than you can update the exposure any time a day and don’t effect the next days update time.

Please take into account, when the framework resets its own counter. Otherwise you might cause a situation where the app allows the user to update the status, but the API rejects it, due to APP and Framework resetting at a different time of the day.

**Comment by ohobby** [comment] 2020-10-31 09:38
Why do I have to open the app regularly to get an exposure update?
Why can't this happen in the background and if something changes to the status "low risk with no contact" you will get a message (in the same way as the message that now asks you to open the app regularly).

**Comment by Ein-Tim** [comment] 2020-10-31 09:42
@ohobby 
Theoretically you don't have to open the App regularly to get an update... This should also happen in the background... Which devices are you using? 

A message that your Risk Status changed will only be send to you if you had a "High Risk Encounter"

**Comment by MikeMcC399** [comment] 2020-10-31 11:18
@ohobby 
Are you using an iOS or an Android device?

**Comment by ohobby** [comment] 2020-10-31 20:59
> Are you using an iOS or an Android device?

@MikeMcC399 
I use iOS

**Comment by Ein-Tim** [comment] 2020-10-31 21:00
@ohobby Which Version of iOS and which version of CWA?

**Comment by ohobby** [comment] 2020-10-31 21:10
@Ein-Tim 

iOS 14.0.1
CWA 1.5.2 (1)
background updates = yes

**Comment by Ein-Tim** [comment] 2020-10-31 21:19
Okay, thanks 👍
You could update to iOS 14.1 and please tell me what Device you are using.
Are Background Checks never happening or are they just shifted back each day (for example: Yesterday the Check was at 20.34h and today the check was on 21.34h) or what Issue are you expieriencing exactly?

**Comment by Blackjacx** [comment] 2020-11-08 23:55
I can confirm this behavior on iOS 14.1 (iPhone XS), newest app version. The update date is a bit later every day:
- 23.45
- 00:14
- 00:52
- etc.

which is weird. Isn't it possible to trigger the update manually? Sometimes I have the desire to run that check 👍

**Comment by Ein-Tim** [comment] 2020-11-09 05:53
@Blackjacx 

> Isn't it possible to trigger the update manually?

Open the App after exactly 24h? 😉

**Comment by Ein-Tim** [comment] 2020-11-20 13:00
With the release of 1.7.0 this Issue is gone since the App will then update all 4h

**Comment by cfritzsche** [comment] 2020-12-03 05:39
With 1.7.1 I think we can close this issue.

**Comment by heinezen** [comment] 2020-12-03 17:21
**Update**

> The Corona-Warn-App updates the risk status at least every 24 hours. The actual time can lag behind for a few hours from the time of the day before.
> Since CWA version 1.7, exposure checks are run up to 6 times per day when a Wi-Fi connection is present. The repeated daily check is performed automatically. While using mobile data, the check is only performed once every 24 hours due to the zero rating commitment of the network providers.

https://www.coronawarn.app/en/faq/#risk_update_24

I think this issue can be considered solved then :) If you are using mobile internet **only**, please use https://github.com/corona-warn-app/cwa-wishlist/issues/281 for continuing the discussion.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-12-03 17:21 UTC
Labels: app, enhancement, mirrored-to-jira
