### ISSUE TITLE
Also show time for suspected contacts

### ISSUE THREAD

**Issue by mxalbert** [corona-warn-app/cwa-wishlist#528] opened 2021-05-18 15:27 UTC
In the current state the App only shows the date of a high risk contact, but not the time.

The time would also be a very useful information in this case, as it would help identifying the place of contact.

I live in a flat directly above a butchery, was it maybe due to folks buying in the butchery, with whom I obviously didn't have any possible contact? A colleague of mine is pretty sure he got the warning from a neighbor in the same house, who was already in quarantine on the date of the possible contact and wasn't even out of his flat the day in question.

---
Corona-Warn-App Open Source Team

Related issues: 
https://github.com/corona-warn-app/cwa-wishlist/issues/198
https://github.com/corona-warn-app/cwa-wishlist/issues/199
https://github.com/corona-warn-app/cwa-wishlist/issues/206
https://github.com/corona-warn-app/cwa-wishlist/issues/266
https://github.com/corona-warn-app/cwa-wishlist/issues/288

**Comment by Ein-Tim** [comment] 2021-05-19 10:29
Hey @mxalbert 

Although @dsarkar already labeled your issue as a duplicate and added the related issues to your OP, I'd like to point out that the Exposure Notification Framework / Exposure Notification System which is maintained by Apple / Google is used by the Corona-Warn-App. This framework records your contacts and sends out the Bluetooth beacons. 
It also hands over the information of an exposure to the CWA, this information does not include the timestamp of the exposure but only the date. 

So this is something what would has to be implemented by Apple & Google into the framework first.

**Comment by heinezen** [comment] 2021-05-20 16:13
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/206

**Closed by heinezen** 2021-05-20 16:13 UTC
Labels: duplicate, enhancement
