### ISSUE TITLE
Native contact database to maintain diary

### ISSUE THREAD

**Issue by pelim** [corona-warn-app/cwa-wishlist#507] opened 2021-05-08 09:18 UTC
## Make use of native Contact Database for diary 

To improve UX of the contact diary the app should request read permission for the contact database. This is would make the the process much easier and the user can choose contacts from his phones and add them to the diary.

### Apple iOS Contact Store

https://developer.apple.com/documentation/contacts

### Android ContactsProvider

https://developer.android.com/guide/topics/providers/contacts-provider

## Is this something you're interested in working on

Yes

**Comment by jucktnich** [comment] 2021-05-08 09:38
I do support this, but this would probably hard to get in the AppStore.

**Comment by heinezen** [comment] 2021-05-09 16:14
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/306

**Comment by pelim** [comment] 2021-05-09 17:11
@Ein-Tim wasn't aware about this restriction from apple

**Comment by Ein-Tim** [comment] 2021-05-09 18:24
@pelim 

No problem. Could you close your issue in favour of #306

**Closed as completed** 2021-05-11 12:12 UTC
Labels: duplicate, feature request
