### ISSUE TITLE
iOS Testflight Invites

### ISSUE THREAD

**Issue by 2x-pr0** [corona-warn-app/cwa-wishlist#276] opened 2020-11-25 20:28 UTC
## Is this something you're interested in working on

Neue iOS oder Android Versionen via Beta Tests anbieten.

**Comment by Ein-Tim** [comment] 2020-11-25 21:01
Although I support your request, I don't think another Issue regarding this is necessary. Please see: https://github.com/corona-warn-app/cwa-documentation/issues/92 for a clear answer about this and also #153 which is mir general, not only talking about iOS but also Android.

**Comment by dsarkar** [comment] 2020-11-26 13:27
Dear @2x-pr0,

Thank you for your request. As @Ein-Tim mentioned, please continue this discussion in our other open issue https://github.com/corona-warn-app/cwa-wishlist/issues/153. See also https://github.com/corona-warn-app/cwa-documentation/issues/214. I will close this issue now, please contribute to the open issue in this case, so we can focus all the information on this topic in one single space.

Many thanks.  Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-26 13:28
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/153

**Closed by dsarkar** 2020-11-26 13:27 UTC
Labels: feature request
