### ISSUE TITLE
Add function to transfer profile/data to a new smartphone or possibility to make backups

### ISSUE THREAD

**Issue by janknieling** [corona-warn-app/cwa-wishlist#542] opened 2021-06-05 09:47 UTC
I think it will be very useful to have a transfer function which can be used to transfer the userprofile/the entire app data to a new smartphone if a user has bought a new one and wants to transfer everything to the new device.
I think this will be an important feature for everyone who has the COVID-19 vaccination certificate into this app because the certificate will be stored locally on the phone.

Alternatively a backup to iCloud or Google Drive function can solve this problem

**Comment by Ein-Tim** [comment] 2021-06-05 10:18
@janknieling 

> I think it will be very useful to have a transfer function which can be used to transfer the userprofile/the entire app data to a new smartphone if a user has bought a new one and wants to transfer everything to the new device.
> Alternatively a backup to iCloud or Google Drive function can solve this problem

This is covered in #8 & #500.
Apple & Google do not allow to back up the data of the ENF (the underlying API which sends, receives & stores the bluetooth beacons). 

> I think this will be an important feature for everyone who has the COVID-19 vaccination certificate into this app because the certificate will be stored locally on the phone.

FYI: You can scan the QR code of the vaccination certificate as often as often as you like on as many devices as you like (see https://github.com/corona-warn-app/cwa-documentation/issues/621#issuecomment-845677846)

**Comment by heinezen** [comment] 2021-06-08 14:23
Hello @janknieling ,

As @Ein-Tim pointed out, this feature request is already tracked in https://github.com/corona-warn-app/cwa-wishlist/issues/8 and https://github.com/corona-warn-app/cwa-wishlist/issues/500. We would like to use the already existing issues to keep the discussion centralized. Therefore, I will close your issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-08 14:23
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/8

**Closed as completed by heinezen** 2021-06-08 14:23 UTC
Labels: duplicate, feature request
