### ISSUE TITLE
move/transfer to a new device

### ISSUE THREAD

**Issue by LasseRheinstroem** [corona-warn-app/cwa-wishlist#231] opened 2020-10-24 09:49 UTC
After buying a new cell phone, one is forced to walk around with two devices for the next 14 days, or at least to check the old cell phone daily.
Please make it possible to move all data to a new device.

**Comment by Ein-Tim** [comment] 2020-10-24 10:04
Duplicate of #8

**Closed** 2020-10-24 10:15 UTC
Labels: feature request
