### ISSUE TITLE
[Android][iOS][UX] TAN validation: clickable input fields

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-wishlist#274] opened 2020-06-17 12:32 UTC
## Describe the issue
The Tan validation shows me which entered number or letter is wrong. The user has to delete all entered signs to correct the false input
## Suggested change
clickable inputfields with a highlighting. So the user can correct easier his code.

---
Internal Tracking ID: EXPOSUREAPP-2885

**Comment by Ein-Tim** [comment] 2020-11-25 15:13
@dsarkar 
I don't know but I thought that the Backlog Repo is a place where Issues are which are worked on, or? So was this worked on but then the work stopped or what? 
Thanks for clarify ❤️

**Comment by dsarkar** [comment] 2020-12-01 11:25
@Ein-Tim, Thanks for your feedback and contributions: You and the community do great work indeed! The Backlog Repo was not really used very much recently. Issues stayed usually in the original Repo, even if they are worked on. 

Regarding https://github.com/corona-warn-app/cwa-wishlist/issues/273, not a bug, rather an enhancement. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-12-04 17:42
I think (if I understand the PR correctly) this will be introduced with: https://github.com/corona-warn-app/cwa-app-ios/pull/1630

**Comment by dsarkar** [comment] 2020-12-05 18:44
@Ein-Tim, well spotted. We will approach the developer as well, and ask if this story can be implemented at the same time. Thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-12-07 18:04
In fact @dsarkar, I think this has already been introduced...
A wrong number in the TAN will be marked like this: 
![image](https://user-images.githubusercontent.com/67682506/101387611-f5942300-38be-11eb-95d9-a34a023285fc.png)

**Comment by dsarkar** [comment] 2020-12-19 11:22
@mrascher-cosee, @Ein-Tim, and community,

We think the current implementation in the CWA version 1.9.1 is a good solution, although not exactly the same as the original proposal by the author of this issue. Nevertheless, we suggest closing this issue after your feedback.

Many thanks for all the contributions. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-21 08:31
@mrascher-cosee, @Ein-Tim, and community,

Closing this issue. Many thanks for all the contributions. Best, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-12-21 08:31 UTC
Labels: enhancement, mirrored-to-jira
