### ISSUE TITLE
Immunity Pass integrated in the Corona Warn App

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-wishlist#453] opened 2021-04-15 13:48 UTC
This is not a new idea, but serves as a container for related discussions.

## Feature description
Include a digital Corona-Free certificate within the Corona Warn App.
The Corona-Free certificate could validate the user's status reflecting that the user is unlikely to be spreading the Corona Virus.

This could be because the CWA user:

1. Has been recently vaccinated against the virus, or
2. Has recently survived a Covid-19 infection, or
3. Has been recently tested for the virus with a negative result.

## Problem and motivation
By including the certificate within the corona warn app, the app would be propagated to reach more users, and this coverage increases it's effectivity.

I [read](https://twitter.com/anked/status/1382433412871507970) that the decision has already been made to include some form of digital #impfausweis in the CWA which is terrifically good news, but nevertheless it makes sense to chart the progress of any discussions (e.g. preserving the faith in anonymity) or decisions here in the CWA github repository.

**Comment by Ein-Tim** [comment] 2021-04-15 13:50
I would consider this as a duplicate of #424 "Integrate with EU's Digital Green Certificate for vaccination, recovery and test".

**Comment by alanrick** [comment] 2021-04-15 13:54
agreed! Sorry - I'd searched for the wrong terms. And I'll delete it.

**Closed** 2021-04-15 13:54 UTC
Labels: feature request
