### ISSUE TITLE
Secure App / "Digitaler Impfnachweis" with Pin/Face ID

### ISSUE THREAD

**Issue by bmaeck** [corona-warn-app/cwa-wishlist#558] opened 2021-06-19 08:25 UTC
## Feature description

As the new feature "Digitaler Impfnachweis" is holding a lot o personal information like name, date of birth, etc. I think it would be great to protect this information via Pin or Face ID. 

It might also be possible to prevent screenshots from being taken in this area of the app in order to increase security.

## Problem and motivation

The change is important for me because I want my personal data to be protected. Especially in case of loss or misuse of the device. I also see the feature as an additional security to ensure that the data corresponds to reality. 

## Is this something you're interested in working on

Yes

**Comment by Ein-Tim** [comment] 2021-06-19 10:01
Closely related to #23.

**Comment by heinezen** [comment] 2021-06-24 16:29
Hey @bmaeck ,

Thank you for your proposal. I would say https://github.com/corona-warn-app/cwa-wishlist/issues/23 already covers your issue, but you are right that this has become increasingly relevant again with even more personal health data being stored. We will bring this issue up to the developers again.

I'll close your issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/23 . Feel free to continue discussing the proposal there.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-24 16:29
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/23

**Closed as completed by heinezen** 2021-06-24 16:29 UTC
Labels: feature request, certificates
