### ISSUE TITLE
Textual input for GUID as alternative to QR-Code

### ISSUE THREAD

**Issue by AnthyG** [corona-warn-app/cwa-wishlist#241] opened 2020-10-29 13:10 UTC
## Current Implementation

Currently, it is only possible to register the lab test by scanning the QR-Code, that one receives, after a finished test.

## Suggested Enhancement

As an alternative to the QR-Code variant of registering the test, provide a text input, where users may input the GUID they get from the test sheet manually.

## Expected Benefits

Users, who are somehow not able to scan the QR-Code (like myself) because of unknown reasons (camera works, and QR-Code content is the same as the printed GUID beneath it, but it does not get recognized by the app, or no working camera), can enter the GUID manually into said text input, and register their test through that.

It might be a bit weird to enter 38 characters or however long the GUID is, but it's better than just not being able to scan the QR-Code.

**Comment by heinezen** [comment] 2020-10-29 14:03
Hey @AnthyG ,

Thank you for the feedback. I think your request matches with the proposal in https://github.com/corona-warn-app/cwa-wishlist/issues/227 . Please give the linked issue a thumbs up, so that we can see how popular the request is overall. To keep the discussion centralized in one place, I will close your issue as a duplicate. Therefore, please continue the discussion in https://github.com/corona-warn-app/cwa-wishlist/issues/227 .

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-29 14:04
Duplicate of #227

**Closed by heinezen** 2020-10-29 14:04 UTC
Labels: enhancement
