### ISSUE TITLE
Bringing additional Information into the Corona App // Local Corona Restrictions & Regulations

### ISSUE THREAD

**Issue by michaelkrause-SAP** [corona-warn-app/cwa-wishlist#235] opened 2020-10-26 11:34 UTC
**Background:**
Some people are feeling, that the value of the App is limited for them. If we look at value drivers for the users, there is one thing, that confuses every citizen. 
**Challenge:** 
What are the “corona rules in a certain federal states or Citys, e.g. with how many people can I meet, when are the restaurants closed”, is there a limitation in wearing masks in certain areas. People are really lost and try to find these kind of information in radio / TV channels. 
**Solution:**
If the App would be able to answer these questions, I guess more people would decide to download & use the app, because it brings additional benefits.

**Comment by achisto** [comment] 2020-10-26 12:10
There are already multiple issues about adding more information to the app currently being discussed. Other users suggested something similar to your request, see their issues: 

#223 Rules and stuff
#222 Display information on local regulations/restrictions
#203 Provide local regulations information
#220 Add information about corona risk areas
#210 Add Inzidenz
#168 Nützliche Informationen in der App

All of the above have been closed in favor of the ongoing discussion in #151 which also fits your suggestion, as far as I can tell. As #151 is the oldest of all the requests and there are already a lot of comments discussing the topic I think it would be best to continue over there.

On a sidenote: #219 with the title "Add "news" from "Corona-Infokanal des Bundesministeriums für Gesundheit" is a bit different from your request but fits what you wrote under "Background" about making the app more valuable, so I feel like this could also be interesting for you. Same goes for #218 (which is still open).

**Comment by heinezen** [comment] 2020-10-27 12:43
Hello @michaelkrause-SAP 

@achisto is right that this is a very popular request from the community and has come up in other issues many times. To keep the discussion centralized, we would like to ask you to have a look at the main thread in https://github.com/corona-warn-app/cwa-wishlist/issues/151 and give the thread a thumbs up or write a comment there if you want to give additional feedback. Giving the post a thumbs up lets us know how popular the request is in the community.

I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/151

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-27 12:43
Duplicate of #151

**Closed by heinezen** 2020-10-27 12:43 UTC
Labels: duplicate, feature request

**Comment by michaelkrause-SAP** [comment] 2020-10-27 12:52
?makes sense !, thanks

________________________________
Von: Christoph Heine <notifications@github.com>
Gesendet: Dienstag, 27. Oktober 2020 13:43
An: corona-warn-app/cwa-wishlist
Cc: Krause, Michael; Mention
Betreff: Re: [corona-warn-app/cwa-wishlist] Bringing additional Information into the Corona App // Local Corona Restrictions & Regulations (#235)


Hello @michaelkrause-SAP<https://github.com/michaelkrause-SAP>

@achisto<https://github.com/achisto> is right that this is a very popular request from the community and has come up in other issues many times. To keep the discussion centralized, we would like to ask you to have a look at the main thread in #151<https://github.com/corona-warn-app/cwa-wishlist/issues/151> and give the thread a thumbs up or write a comment there if you want to give additional feedback. Giving the post a thumbs up lets us know how popular the request is in the community.

I will close this issue as a duplicate of #151<https://github.com/corona-warn-app/cwa-wishlist/issues/151>

Regards,
CH

________________________________

Corona-Warn-App Open Source Team

-

**Comment by Ein-Tim** [comment] 2020-10-27 20:45
@heinezen I think it would be sensefull to pin #151 (and #138) so people stop creating new Issues requesting this Features. 
Thanks and Thank you for your work! 👍❤

**Comment by heinezen** [comment] 2020-10-29 14:09
@Ein-Tim I think we can do this. We just have to update README to mention the pinned issues because in my experience people still tend to overlook those. I'll check back to see what the most popular request were and pin them.

**Comment by Ein-Tim** [comment] 2020-10-29 15:39
@heinezen Thank you, could you keep me up to date about this pls? Thanks! ❤️
