### ISSUE TITLE
PDF export for QR Codes generated by the website

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-wishlist#493] opened 2021-04-29 15:48 UTC
## Current Implementation
QR Codes generated by the website are only available as PNG picture.

## Suggested Enhancement
QR Codes generated by the website should be available as PDF file.

## Expected Benefits
The PDF format is very common and easy to use, even when creating new QR Codes with tablet devices or desktop computers. Also in my opinion the printing process is more easier for printing documents than printing photos (scaling, rotation, etc).

**Comment by Ein-Tim** [comment] 2021-04-29 15:53
Hey @FlightMS 

I'd say we should merge this with https://github.com/corona-warn-app/cwa-website/issues/1149, which also mentions PDF.

If you think so too, feel free to close this issue.

**Comment by heinezen** [comment] 2021-04-29 15:53
Hey @FlightMS ,

Thanks for the proposal. However, this request is already tracked in https://github.com/corona-warn-app/cwa-website/issues/1149 in the website repository. Please consider contributing to the discussion there.

I will close your issue as a duplicate

----
Corona-Warm-App Open Source Team

**Comment by heinezen** [comment] 2021-04-29 15:53
Duplicate of https://github.com/corona-warn-app/cwa-website/issues/1149

**Closed by heinezen** 2021-04-29 15:53 UTC
Labels: enhancement
