### ISSUE TITLE
reporting correct count of currently exposed users (RandomIDCount / Bereitgestellte Schlüssel) 

### ISSUE THREAD

**Issue by ST4YHealthy** [corona-warn-app/cwa-wishlist#89] opened 2020-07-01 15:51 UTC
## Current Implementation
The concrete values of the periodically sent "ExposureChecks" from central server to every single smartphone.
Concrete dataElement: "RandomIDCount"

## Suggested Enhancement
To know how effective the use of the corona-warn-app really is, it would be very interesting to know the exact value of the "RandomIDCounts" transmitted by the central server.
To be honest, I do really not understand why it should be a data privacy risk if these values would be the "correct" ones.

## Expected Benefits
Users would not have to spent a lot of time to have a look on the web to get these very interesting information!
If not possible - somehow integrate an URL into the app where the user could find these information.
To wait for some of the developers or devOps Members to make these value public is not very satisfying

# Example: 
On 24th of june with Hash F5430B4B125B23E7D714C49745DD90BEBF53CB3A697EE940322B69FE24D43EC2 the RandomIDCount transmitted was 503
On the web some developers announced, that these "first" 503 IDs would reflect 30 real infected persons.
That's a factor of 16,77 -> maybe the app should somewhere and somehow just show this factor.
This would be very nice and very helpful.

Imagine the RKI or JohnsHopkins publishes 1.000 current exposures per day in germany
Imagine the protocol on your smartphone publishes randomIDCounts matching the math: 1.000*factorX for this day
--> The user would now know, that every infected person has published it's exposure. "What a wonderful world" ;-) 

-------
Internal tracking Id: [EXPOSUREAPP-2106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2106)

**Comment by christian-kirschnick** [comment] 2020-07-02 14:28
The app does not know how many people reported themselves as positive. Not even our backend knows that. 

You can make some educated guesses based on the knowledge on how keys are generated, but it will not give you accurate values - it will always be an estimation.

The community came up with some dashboards which may give you some more insights: https://micb25.github.io/dka/

**Comment by SonaliDK** [comment] 2020-08-11 07:44
Hi @ST4YHealthy,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment] 2020-10-26 20:35
> The app does not know how many people reported themselves as positive. Not even our backend knows that.

Well - *somewhere* in the system these numbers could be availabe.
E.g. the server that receives a package of DEK keys and inserts them into the database could increment a counter

**Comment by Ein-Tim** [comment] 2021-07-16 16:36
Has this been implemented with the "Warning by App Users" statistics card? Or do I misunderstand something?

**Comment by gh47110815** [comment] 2021-07-16 19:02
Yes, issue meanwhile no longer exists . Ticket can be closed.

**Comment by Ein-Tim** [comment] 2021-07-16 19:07
Thanks for the update @gh47110815! You, as the author of this issue, should be able to close the issue.

**Comment by heinezen** [comment] 2021-07-18 12:06
I'll close the issue for you, since it's considered solved.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-07-18 12:06 UTC
Labels: Fix 1.12, enhancement, mirrored-to-jira

**Comment by Ein-Tim** [comment] 2021-07-18 12:10
@heinezen 

Statistics were implemented with version 1.11, so I think the `Fix 1.12` label is wrong here 😅

**Comment by heinezen** [comment] 2021-07-18 12:32
@Ein-Tim https://github.com/corona-warn-app/cwa-app-android/pull/2043 on Android is for 1.12. Or am I misremembering something?

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-07-18 12:36
@heinezen No idea why this PR merged into 1.12, but here's the 1.11 blog post: https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11/ and here are the GitHub releases, all speaking of the statistics: 
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.11.0 & https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0.

**Comment by heinezen** [comment] 2021-07-18 12:43
@Ein-Tim Thanks. Turns out the feature was intended to be in 1.12, but got moved back to 1.11 (see https://github.com/corona-warn-app/cwa-app-android/pull/2192). The Jira ticket for the statistics feature still said 1.12, so the development was faster than the initial planning!

----
Corona-Warn-App Open Source Team
