### ISSUE TITLE
Choose app language in settings

### ISSUE THREAD

**Issue by w-sky** [corona-warn-app/cwa-wishlist#509] opened 2021-05-09 08:20 UTC
Hello there, currently the app (Android) always uses the same language as the phone system language.
But sometimes it is useful or necessary to choose another language. E.g. if you want to show the app to someone who does not understand your language. And any other reason.

Expected place to change app language: Settings in app main menu.

**Comment by Ein-Tim** [comment] 2021-05-09 08:25
Hey @w-sky 👋

Thank you for contributing here!

We have a very similar issue for this already: #22
If you think that #22 covers your proposal, I suggest that you close this issue here, monitor #22 and follow up there if necessary. 

Thank you, stay safe and enjoy Sunday!

**Comment by Ein-Tim** [comment] 2021-05-09 08:29
BTW it is possible to change the language under iOS, see [this](https://github.com/corona-warn-app/cwa-wishlist/issues/22#issuecomment-824746939) comment in #22.

**Comment by heinezen** [comment] 2021-05-09 16:14
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/22

**Comment by heinezen** [comment] 2021-05-11 12:13
Closed as duplicate

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-05-11 12:13 UTC
Labels: duplicate, feature request
