### ISSUE TITLE
Display information on local regulations/restrictions

### ISSUE THREAD

**Issue by Lutz13** [corona-warn-app/cwa-wishlist#222] opened 2020-10-21 11:38 UTC
## Feature description
It would be great to be able to view information on the regulations and restrictions currently valid and/or planned for a given area (country, federal state, city, area, ...). The user should be able to give consent to the app to retrieve the current location abnd use this as selection for the initially selected location; the user should not be forced to give such consent, and in that case he should be able to search for a location.

## Problem and motivation
There are so many local regulations/restrictions, changing frequently, so it is difficult to track how one should behave at the current location. E.g. do I have to wear a mask insider or in the open, how many people are allowed for a party, a wedding, at what time do restaurants, bars etc have to close, and much more.

## Is this something you're interested in working on

Yes. But I never worked on developing an App; maybe I could work on the backend functionality.

**Comment by Ein-Tim** [comment] 2020-10-21 12:14
Duplicate of #151

**Comment by heinezen** [comment] 2020-10-22 15:28
Hello @Lutz13 

Thanks for the feedback. We already discuss the proposal of adding local regulations to the app in https://github.com/corona-warn-app/cwa-wishlist/issues/151 . Please continue the discussion there to keep it centralized and give the issue thread a thumbs up so that it gets more attention from the devs. 

This issue will be closed by me as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-22 15:28
Duplicate of #151

**Closed by heinezen** 2020-10-22 15:28 UTC
Labels: feature request
