### ISSUE TITLE
Get QR-Code from Picture directly vom CWA

### ISSUE THREAD

**Issue by riedborn** [corona-warn-app/cwa-wishlist#613] opened 2021-08-12 13:52 UTC
It would be very nice to get the QR-Code that I've got via Email directly from the pdf or from a screenshot taken from the pdf.

Wolfgang

**Comment by jucktnich** [comment] 2021-08-12 13:57
Duplicate of #389

**Comment by heinezen** [comment] 2021-08-19 11:00
Hey @riedborn ,

I assume you want to have the same feature as already discussed in https://github.com/corona-warn-app/cwa-wishlist/issues/389. The feature is planned for a future version of the app. You can subscribe to the linked issue for updates on the matter. I'll close your issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/389

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-08-19 11:00
Duplicate of #389

**Closed as completed by heinezen** 2021-08-19 11:00 UTC
Labels: duplicate, feature request

**Comment by ndegendogo** [comment] 2021-08-19 19:12
> The feature is planned for a future version of the app.

@heinezen nice! Thanks! 🎉
