### ISSUE TITLE
Rules and stuff

### ISSUE THREAD

**Issue by trassenjohnny** [corona-warn-app/cwa-wishlist#223] opened 2020-10-21 14:02 UTC
hi, im not a dev so it will sound quite noobish.
there should be an feature where u can lookup your hometown within in the app and get all the infos about rules and numbers about your town. would be the easiest way to double check all the changing info u get on a daily basis by either broadcasting or by others.

**Comment by Ein-Tim** [comment] 2020-10-21 14:41
Duplicate of #151

**Comment by heinezen** [comment] 2020-10-22 15:12
Hey @trassenjohnny ,

There already is a discussion for this in https://github.com/corona-warn-app/cwa-wishlist/issues/151 as @Ein-Tim pointed out. Please give the post there a thumbs up or a heart so we can determine how popular the feature is.

Thanks

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-22 15:12
Duplicate of #151

**Closed by heinezen** 2020-10-22 15:12 UTC
Labels: feature request
