### ISSUE TITLE
Make data export- and importable

### ISSUE THREAD

**Issue by bhausen** [corona-warn-app/cwa-wishlist#172] opened 2020-08-31 07:42 UTC
## Feature description
Add a functionality to export exsting data and reimport data.

## Problem and motivation
When moving to a new phone all data is lost. 
Problematic scenarios:
* If a person met before the move gets tested positive, I am not any longer available to get information about this.
* If I added the QR code of a test into the app and moving to new hardware, the testing result will get lost. In case of a positive test nobody will get informed about it.

## Is this something you're interested in working on
No

**Comment by tkowark** [comment] 2020-08-31 08:35
Thanks for the propsoal. Something like that is already being tracked in #8 or do you have something else in mind?

**Comment by bhausen** [comment] 2020-08-31 08:43
Did not find #8. Sorry, please mark this as a duplicate. 
But it is disapointing not being able to transfer the data to a new phone...

**Comment by abro1i** [comment] 2020-08-31 09:39
Duplicate of #8

**Comment by abro1i** [comment] 2020-08-31 09:39
Since this is a duplicate, i will close this now.

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Closed by abro1i** 2020-08-31 09:39 UTC
Labels: feature request
