### ISSUE TITLE
Provide local regulations information

### ISSUE THREAD

**Issue by raue** [corona-warn-app/cwa-wishlist#203] opened 2020-10-12 08:40 UTC
## Feature description
Providing local corona regulations or status available in app.
Due to the fact, that special/different regulations may get applied to certain regions in one country (e.g. Germany), it would be helpfull getting to know what's allowed. So by having the localization information available, a kind of look-up in order to pull the corona status information would proposed.
 

## Problem and motivation
As  said before, folks in Germany getting confused about what is allowed and what is not allowed wrt. the current location. Since the mobile phone has the GPS position available, a link to the local regulations should be obtainable. So at the end, you would have clear indication what's going on at your current location, rather than guessing, asking others, googling, etc.
## Is this something you're interested in working on

<!--- Yes or No ---!>

**Comment by Ein-Tim** [comment] 2020-10-12 11:48
Duplicate of #151 
(Or very similar)

**Comment by raue** [comment] 2020-10-13 06:52
yes, #151 would so far cover, what I've in mind. Having such a feature, would be probably beneficial for surviving the current chaos when the questioncomes up of how to deal w/ the many different regulations.

**Comment by heinezen** [comment] 2020-10-13 10:16
Hey @raue 

I will close this issue as a duplicate then, so that it's easier to track the discussion. Thanks again for the feedback.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-13 10:16
Duplicate of #151

**Closed by heinezen** 2020-10-13 10:16 UTC
Labels: feature request
