### ISSUE TITLE
Add a warning confirmation dialog when removing a test without result present

### ISSUE THREAD

**Issue by bhausen** [corona-warn-app/cwa-wishlist#173] opened 2020-08-31 07:49 UTC
## Feature description
Add a confirmation dialog when removing a test without a result already present. This confirmation dialog need to make it clear: **There is no way to add the test once again to this or to any other phone to check the test result.**

## Problem and motivation
Two of my children got tested. I added the first QR, saw the results not being present so far, removed it and added the second one to verify this one. One day later I removed the second test to add the first one again. But this was not possilbe.

We got informed about the test results by the doctor, but for that no corona-warn-app is necessary.

## Is this something you're interested in working on
No

**Comment by bhausen** [comment] 2020-08-31 07:56
Is more an enhancement than a feature request.

**Comment by Ein-Tim** [comment] 2020-08-31 09:45
This looks for me like a duplicate of #144

**Comment by bhausen** [comment] 2020-08-31 09:48
If you split #144 into its three requests, than it might be a duplicate of a).

**Comment by Ein-Tim** [comment] 2020-08-31 09:52
It seems like a) is the only way to go because of data protection.
See @daimpi's comment [here](https://github.com/corona-warn-app/cwa-wishlist/issues/144#issuecomment-669323596)

**Comment by bhausen** [comment] 2020-08-31 10:29
Ok accepted as duplicate. Is there any place to vote for #144? It is realy bad, that there is no warning at this test removal.

**Comment by thomasaugsten** [comment] 2020-08-31 10:35
Hi @bhausen 
In 1.2.1 there is this warning included:
![Uploading IMG_3525.PNG…]()

Sorry if this warning is misleading, we will improve the text in 1.3 for a better understanding.

**Comment by daimpi** [comment] 2020-08-31 11:58
@bhausen 
I think your problem is also somewhat related to https://github.com/corona-warn-app/cwa-wishlist/issues/109, because there is currently no way to add multiple tests in your app (like e.g. for your children). 

I hope we see some improvement on this front as well :)

> Ok accepted as duplicate. Is there any place to vote for #144?

Yes, just click on the thumbs-up button on the first post, or any post you like 🙂

**Comment by bhausen** [comment] 2020-08-31 12:12
Yes, the warning is missleading. It tells you if you remove the test, you remove the test. But it need to be very clear: YOU CAN NOT ADD THE TEST TO ANY DEVICE ANY MORE, IF YOU REMOVE IT NOW!

**Comment by bhausen** [comment] 2020-08-31 12:17
You are allowed to use capitals in this message. Only then the users will understand.

**Comment by Marco2907** [comment] 2020-08-31 14:03
Hi @bhausen, thanks for sharing your content. I would close this issue because as @Ein-Tim mentioned, it is similar with #144 

Thank you.

Best,
MP 

Corona-Warn-App Open Source Team

**Closed by Marco2907** 2020-08-31 14:03 UTC
Labels: duplicate, feature request
