### ISSUE TITLE
Adding a 'virus-free again' feature

### ISSUE THREAD

**Issue by Leonard-Reuter** [corona-warn-app/cwa-wishlist#115] opened 2020-07-13 09:33 UTC
Having just read [this article](https://www.zeit.de/digital/mobil/2020-07/corona-warn-app-positives-ergebnis-infiziert-reaktion):

For people, who were infected, but whose virus tests are now negative again, the only option is to remove the app from their phones. Otherwise, everybody around them would always be alerted for COVID exposure.

Yet, since the duration of post-sickness immunity is not really clear, there should be a way for those people to continue using this app. Similarly to submitting a positive test result, there should be a way to submit the negative test results you need in order to be labelled virus-free.

---

Internal Tracking ID: EXPOSUREAPP-2074 Story request
EXPOSUREAPP-4641 Android
PR Android corona-warn-app/cwa-app-android#2230 and
PR Android corona-warn-app/cwa-app-android#2253
EXPOSUREAPP-4781 iOS
PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/1960

**Comment by daimpi** [comment] 2020-07-13 21:31
> Otherwise, everybody around them would always be alerted for COVID exposure.

This is not the case, which is also mentioned in the Zeit article: 

>[…]Es würden nur die Kontakte informiert, die bis zum Zeitpunkt der bestätigten Infektion erkannt würden.

Only Keys up to the point of entering the TAN will be uploaded to the server and can therefore warn other people. Every contact after that will not see that they had a risk contact, even if the App shows a "red" risk status for the infected. The assumption is that people are behaving responsibly by self-quarantining. 

But yes: I agree that in general it seems like a good idea UX wise to have a user-friendly way to enter a non-infectious status in the app after quarantine, even though technically resetting the app would work just fine.

**Comment by tobstac** [comment] 2020-07-14 13:53
> Only Keys up to the point of entering the TAN will be uploaded to the server and can therefore warn other people.

I am not sure whether every app user is aware of this. There might be cases (emergencies, whatever) where people have to leave quarantine even while being aware of the infection and still trust the app to warn other people. Indeed, in such a case, contacts should still be informed - which is only possible if keys are still uploaded, which again is only sensible if there is a feature to reset the status to non-infected.

Alternatively (or additionally), how about limiting the infected status to a specific time period. After all, we know people are only infectious for a given time after which they should be able to leave quarantine again without unnecessarily alerting other contacts or having to skip using the app. This would also help to reduce false-positives if people just forget to clear their status after they recovered.

**Comment by daimpi** [comment] 2020-07-14 16:23
See [here](https://github.com/corona-warn-app/cwa-documentation/issues/326) for discussion on the topic. One reason why the TANs are not allowed to validate future keys is that this could invite abuse: you could generate any number of RPIs with it and broadcast them everywhere to generate a large amount of false positive warnings. 

If someone is tested positive and gets into contact with other people afterwards even though they should be self quarantining, the best that could probably be done is to give them another TAN later on.

**Comment by Ulenrich** [comment] 2020-07-14 19:10
The ultimate virus-free feature: 
Automatic de-installation of the app from the smartphone and added a reminder to the users calendar ca 100 days later to re-install the app because immunization to the Sars-Cov-2 virus might decline after this period.

**Comment by informationiskey** [comment] 2020-10-22 16:53
may we change the feature title in a more general one:
"ADD a negative Test-Result" + "and share it actively" [consent for making it named/public/visible] 
- From yourself
- From your Kids

Background: What we see right now, is in Public a big questionmark on the App beeing effectful.

What we can learn from the also very effectful Stuttgart21 and the therefor to late but than started "citizen involvement" are 2 Key facts to get people involved and "on board"
1. Transparency
2. Active involvement
What we also can learn from the very successful Big 5 Social Media Players is the one and only Key fact:
3. Value Add

So for 1) - We do need to have a Reporting Page with a beautiful Curve or a list like featured already in #199 or in #196 
showing up all the contacts I have had. Emphasized on "ALL" - including Negative ones.

Why
For 2) - I suggest including the possibility to add your Negative Test Result as well as the Negative Test Result for your KIDS.
Beside the fact, that we are proud to be Negative - and also spend a lot of Money and time in those testing results - again and again - this would be the right feature to minimize the fear of sharing my results with others - I easily share a negative Testresult!

The second effect is - with the new build-in Reporting page - actualized in real-time by the App directly, not through the server every 24h - I easily could integrate this in the running discussion - if the app is working or how it effects me - they just can see me and my negative results - in their reporting - right now.

This would open up in my opinion a lot of barriers and fearing behaviours - "hey - the app is working: look - we are negative"

And also a side kick - for sure the statistical guys in RKI can use use this created trustful negative base to calculate the real positive effects better.

**Comment by Ein-Tim** [comment] 2020-10-22 17:47
@informationiskey 

While I in general agree with your proposal, please think about two things:

1. The heavy Server Load if it would be possible to share negative Test Results. And not only the Load on Server, but also User Side. The storage of some devices will run out very fast - which leads to deinstallation.
2. The number of non positive contacts is not revealed to CWA by the ENF - so in theory (if we would stay with the GAEN Framework) even if somebody is negative - he must be marked as positive so ENF exposed the Data to CWA - and then the next question is: How do you distinguish between real positive Encounters and fake positive Encounters...

**Comment by informationiskey** [comment] 2020-10-22 18:12
@Ein-Tim 

Meanwhile I Understand in general your point, but only in the context of the actual design I found here:
https://github.com/corona-warn-app/cwa-app-ios/issues/678#issuecomment-646686363

But - leave us the technical design part away for a second. 
Customer design thinking - What would help the citizen most, not the RKI, and not the Gesundheitsamt.

What we have right now, is only solving the first core basic part - we somehow now there might be a contact.
For the very positiv thinking and trustful citizen and so on - this is ok.

But what we are facing - as always in big crowds - is a much more divers and critical and not understanding big number of people.

So to reach that we (I say we as the developer community mainly talks here ;-)  - and you see that in the big fives social activities par excellence - have to first think of - what would be sexy enough everybody wants to use it.
As I can see from all the discussions so far - there have been at the very first core decision - one that fulfill the highest security levels. Which I understand as a very conscious german contra point to all the US - open data collection solutions.
fullfilled - and also in the big crowd no doubt.

But now - it must go to the next level of "sexyness" - and probably this means - as far as I understood this underlaying framework - a  secondary App - either embedded or linked or somewhat referenced with this one - fullfilling that crowd necessary information layer.

**Comment by daimpi** [comment] 2020-10-23 02:12
@informationiskey I don't think it's a good idea to share negative Temporary Exposure Keys (TEKs) with the server and other users as @Ein-Tim already pointed out: this would **significantly** increase the load on the infrastructure.
But it also weakens the privacy posture of ppl who tested negative b/c their rolling proximity identifiers (RPIs) can now be chained over the whole day.

And tbh I don't see that we would get much value out of this: 
- test positivity rate is something RKI already has data on, they get this info directly from the labs and don't need an app for this
- number of "negative tested" CWA contacts is not something I would think of as particularly interesting and/or useful information and it's certainly not actionable.

Btw: if you want to get more info on encounters, I can highly recommend the [warn-app-companion](https://github.com/mh-/corona-warn-companion-android) if you're running Android. You don't even need root, as you can simply run it in RaMBLE mode 🙂.

**Comment by informationiskey** [comment] 2020-10-23 06:00
Understood so far from the technical framework. For the part "particularly interesting /useful" I would suggest to have a customer survey.

**Comment by ndegendogo** [comment] 2020-10-28 19:41
*I have a request for a different feature, maybe somewhat related.
Not sure if I should raise it here, or open a separate ticket.*


### Problem and motivation

**Scenario:**

- on day 1, I have a contact to an infected person
- the person gets tested positive on day 2, and shares their DEK keys with cwa
- I download these keys on day 3 and get a red warning
- I am a good citizen. I go home at once, self-quarantine, and get advice from my doctor / the health authorities.
- on day 4 I get a lab test, and luckily it is negative. 
- on day 5 I go back to work and out into the dangerous world with infection numbers exploding around me.

But my cwa warning is still red, and will stay so for another 9 days till my risky contact fades out. And I know that I have mitigated the initial reported risk with the lab test, but now I am blind, and will get no further warning beyond the already-red screen.
And this feels weird, especially as I have used cwa actively now for 4 1/2 months.

I want to tell cwa that I have mitigated the initial risk, and I want it to ignore this risky contact, and turn green again, and to warn me again of the next risky contact. And I want this now, without having to wait another 9 days.


### Feature description

I want a dialog where I can enter my "negative" test result. At any time, not related to any prior DEK key upload. And this fact will not be submitted to the server, it **stays locally on my device**, but **has an impact on my risk assessment / risk status**.

Of course the details of such a feature need to be adviced by RKI. My naive assumption is that cwa could ignore the key files older than the lab sample taken, plus maybe a few days for the incubation period. Even better if it could filter the encounters by this condition (but I guess this would have to be implemented in ENF?)

No special plausibility checks needed here. Can be a QR code or even manual input. The lab needs not even be integrated to cwa interface.

**Comment by rugk** [comment] 2020-10-28 20:45
IMHO this is a new issue. But I'm not sure whether CWA would not tell you "You had two risk contacts" if you meet another infected person?
If it does that, you don't need to tell the negative test result.

**Comment by ndegendogo** [comment] 2020-10-28 21:01
@dsarkar From what is proposed and discussed here, my proposal at #239 is a different feature.
Could you please reopen it?

Of course, I don't know the scope and focus of your internal ticket you mentioned.

**Comment by Ein-Tim** [comment] 2020-10-28 21:03
@rugk The problem is that the "Days since Encounter" in the High Risk Card are not correct: https://github.com/corona-warn-app/cwa-documentation/issues/422

Also if you have a High Risk Encounter than there is the Quoute: "n Risiko Begegnungen", but there also Low Risk Encounters are included.

And on top of that, if you have a High Risk Encounter and you have another High Risk Encounter and the first Encounter is not yet older than 14 days, there will be no push notification send to you.

**Comment by ndegendogo** [comment] 2020-10-28 21:29
@rugk actually, the day before I got "red", it was even 5 contacts, but still green. Next day it was red with 6 contacts. And while I was in quarantaine I got another (red, 7 contacts). Now they start to fade out.

To answer your question: Yes, I would see if another one appears. But I cannot see if the new one is red or green.

**Comment by dsarkar** [comment] 2021-02-11 10:02
@Libavius  @MikeMcC399 @Ein-Tim @ndegendogo 
FYI PR corona-warn-app/cwa-app-ios#1960 (Fix 1.13 planned)
seems to solve this issue in a more elegant way?
What do you think?

**Comment by ndegendogo** [comment] 2021-02-11 10:36
@dsarkar the PR refers to Jira ticket 4781 which I cannot see, so I can only guess.
What I see in the screenshots and what I imagine looks good to me.

By the way, I understand that "end-of-life" relates to the life cycle of the app (not the user!) - **but, please, use this wording never ever in any communication towards the public!** - just imagine a user just got her test result, covid-positive, and then hears "end-of-life" ... 😱

**Comment by MikeMcC399** [comment] 2021-02-11 10:46
@ndegendogo 
EOL is not a good term for external communication, I completely agree. In terms of health, it means something very bad, and in terms of software I've always seen it used in conjunction with withdrawal of support, which is also not something a user would want to see.

"Restart exposure logging" is what is effectively being done.

**Comment by MikeMcC399** [comment] 2021-02-11 10:47
@dsarkar 
> FYI PR corona-warn-app/cwa-app-ios#1960 (Fix 1.13 planned)
seems to solve this issue in a more elegant way?
What do you think?

My answer is the same as in https://github.com/corona-warn-app/cwa-wishlist/issues/347#issuecomment-777353152

iOS Feature/4781 end of life behaviour seems to resolve the request.

I found EXPOSUREAPP-4641 for Android:
corona-warn-app/cwa-app-android#2230 and
corona-warn-app/cwa-app-android#2253

**Comment by Ein-Tim** [comment] 2021-03-05 06:32
Hey @Leonard-Reuter 

Version 1.13 which introduced this has been released to GitHub and is available to all users in the next 48h.

See blog post:

DE: https://www.coronawarn.app/de/blog/2021-03-04-corona-warn-app-version-1-13/
EN: https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.2

Please close this issue.

**Comment by heinezen** [comment] 2021-03-14 13:19
Dear community,

Thiis feature is now implemented in CWA v1.13. Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-03-14 13:19 UTC
Labels: Fix 1.13, feature request, mirrored-to-jira, ready-to-close
