### ISSUE TITLE
Ensure the app works correctly after restoring an iPhone

### ISSUE THREAD

**Issue by heddy71** [corona-warn-app/cwa-wishlist#177] opened 2020-09-04 13:34 UTC
I've been using the app since day one on my iPhone XS. When I broke the screen of this phone, I created a backup, restored this backup onto a loaner device (iPhone X) and sent my iPhone XS in for repair.
The app was available on the loaner device as part of the restored backup and I never opened it. When I did, the following happened:
1. The app presented the welcome screen that usually appears when starting it for the first time after installation.
2. I tapped through the screens where you have to grant authorizations and allow notifications.
3. When this was done, the app presented the initial welcome screen again.
4. I tried again a couple of times, but it appeared to be an endless loop.
5. I removed the app and installed it again.
6. This time, everything worked fine and only here, I was actually presented with the iOS popups where you confirm that recording encounters is allowed and notifications can be sent by the app. In steps 1-4, this never happened.

The problem I see is that people may not check whether the app works correctly after restoring an iPhone, because other apps do work without re-initialization. So this malfunction may go unnoticed for some time (as in my case).

**Comment by abro1i** [comment] 2020-09-07 07:26
Hi @heddy71,

thanks for your feedback. 

This issue has already been mentioned. You can actually see a screen recording of the issue here:
https://github.com/corona-warn-app/cwa-app-ios/issues/754#issuecomment-682499237

Best regards,

ABB

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment] 2020-09-07 07:26
Duplicate of #754

**Closed by abro1i** 2020-09-07 07:26 UTC

**Comment by abro1i** [comment] 2020-09-07 07:30
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/754
