### ISSUE TITLE
[Feature Request] QR code scanner for IDs of (indoor) locations

### ISSUE THREAD

**Issue by medienintegration** [corona-warn-app/cwa-wishlist#70] opened 2020-05-15 09:58 UTC
Virologists point out that the virus appears to spread in over 40% of the infections caused by aerosols, which can remain in the air for up to several hours in closed rooms. I think it could be helpful to create a possibility for restaturants, hairdressers etc. to be part of the tracing process without using a Bluetooth device, e.g. with the help of QR codes.

Guests would scan the respective QR code when entering and leaving such a store and the app would rate the transmitted IDs as contacts. If it turns out that an employee has tested positive for Corona, the IDs would be uploaded to the backend server as infected and all guests who have been in this room in e.g. the past 2 weeks (or five days before the onset of symptoms) will be informed by the app.

Such a solution would require a server that provides IDs based on a public url for the participating shops / locations.

----------
Internal Tracking Id: EXPOSUREAPP-2124

**Comment by tkowark** [comment] 2020-06-26 13:03
Reopening now as part of the wishlist.

**Comment by wMATTI** [comment] 2020-06-30 15:55
This great idea could finally put an end to the prevailing problem with the registration on paper for visiting localities and would be finally compliant with gdpr. Could also increase the attractiveness of the app and the number of users.

Could be so easy:  

![Corona_dsgvo-konforme-Gastanmeldung_Gast-Screen](https://user-images.githubusercontent.com/67647005/86148005-5c383800-bafa-11ea-9683-58a77bd20c7b.jpg)
![Corona_dsgvo-konforme-Gastanmeldung_Anmelder-Screen](https://user-images.githubusercontent.com/67647005/86148006-5cd0ce80-bafa-11ea-9c8a-f4584da2b251.jpg)

**Comment by medienintegration** [comment] 2020-07-02 07:30
If I understand the specifications of Google's and Apple's API correctly, there is no way to add your own IDs that are not received via Bluetooth to the collection of transmitted IDs. But maybe there is still a possibility to include locations in the tracing process and to use parts of the CWA infrastructure for this.

As already described, this would require a server that provides IDs that are assigned to locations via public links. As a location, I would have to register with name, address, logo etc. and would receive the link in the form of a QR code, which visitors can scan when entering and leaving the location. To confirm that this QR code is correct, the app could display the name / address / logo it received from the server.

The app would save the provided IDs / timestamps regardless of the BLE IDs. If a positive Corona case is associated with a participating location, the relevant IDs would be published and the app could carry out a risk calculation and inform the user if necessary. The configuration parameters (duration risk, days risk) of the RKI could also be used for this calculation (or differ in the case of a different recommendation).

This function could be added to the app as a feature / plugin, which is deactivated by default, so that the users could decide whether they would like to use this function.

I know that this feature would probably be enough for another single app and, as @TomTeeJay emphasized, the mix of features could be problematic. Nevertheless, I find such a feature worthy of discussion due to the success of the app and the current problematic visitor tracking in restaurants and other locations.

**Comment by alanrick** [comment] 2020-07-31 15:17
I understand @tkowark ‘s statement that this is not in the scoping document, but is that by design or lack of foresight? Similarly, it is one thing if the current BLE API does not support this but quite another if the topic hasn’t been broached with Google/Apple. 

I ask because I found it very convenient and hygienic in the UK to use qrcodes taped to the pub tables to register, and at the same time I notice a deterioration in friends’ willingness in Germany to submit correct details in the bar lists. Squirting Random IDs into a local (cloud) server would be more private and comfortable. 

Ultimately, it’s RKIs call. But it does seem a wasted opportunity not following up on this armed with tracing-center success/failure statistics and  epidemiologist, psychologist and IT expert opinions.

**Comment by f-re** [comment] 2020-09-09 09:17
Strongly support this, as NFC and as QR code solution.
To mitigate misuse by copy (for unsigend NFC or QR) possibilities are:

- the codes as stickers can be replaced quickly by just using a new QR sticker.

- indirect to a server URL that issues a fresh UUID. The server can disable abused QRs centrally.

This is also a good solution for public transport ("scan when enter"). As users only touch their mobiles I see the risk of creating local hotspots quite low.

**Comment by jniediek** [comment] 2020-11-17 13:28
This was issue #272 previously, now moved here due to overlapping scope. Note however that the proposal below goes beyond a mere addition to BLE-based ID transmission.  

## Feature description

As repeatedly discussed by Prof. Drosten and others, it's crucial to identify infection clusters. Here is an idea towards this goal.

1. Create a website to print specific QR codes. These printed codes are used to identify rooms or closed spaces in general, such as class rooms in schools, offices, workplaces, restaurants, maybe even train compartments. Anybody can print a code and display it inside the room. Each QR code contains two pieces of information: a **unique ID** (generated by the backend behind the website) and some **nickname for the room** (not necessarily unique, such as "McDonald's at Berlin Hbf" or "Commerzbank München Office 210"; provided by the user who prints the QR code). For privacy concerns see below.

2. Use CWA to scan the QR code when you enter a room. The unique ID is stored **only locally on the device**, and the nickname of the room is stored **only locally on the device** in the form of some "my closed rooms diary" together with a time stamp, visible to the user of CWA. 

3. If a user is tested positive, three things happen:

- The user can send his/her list of room nicknames to the health authorities/Gesundheitsamt. This will improve the contact tracing interviews a lot: they will be **more precise, more complete, and faster**, because the list of visited rooms will help the patient to recall what happened during the last 14 days. For privacy, of course the user will be able to delete items from the list before sending, and of course sending the list will be voluntary at any time. This is the main benefit of the suggested feature. Additionally:

 - The scanned room IDs + timestamps will be used in the same way that CWA is working right now: The patient can (voluntarily) upload the list of scanned unique room IDs, CWA can download the list, and CWA can then display a warning to anybody who scanned the same ID at around the same time: "a covid patient was in the same room with you". This could be more precise than the current BLE for example in restaurants or offices with bad ventilation, where people can sit 20 m apart and still catch the virus through aerosols.

- The server side of CWA can compute statistics on room IDs scanned by people tested positive to find infection clusters. These highly relevant room IDs can be downloaded by CWA, which can then display a warning such as "you were in a room where several people got infected. Please inform the health authorities". This could help the health authorities to prioritize some investigations above others. For example, they could call contacts of somebody who was found to be in a cluster situation earlier  than contacts of somebody who was not found to be in such a situation.


## Problem and motivation

Current problem: contact tracing interviews are slow, and results are imprecise and incomplete. Imagine people had the option to quickly scan a QR code every time they go into a closed room. This would greatly improve the outcome of contact tracing interviews. Furthermore, it would have positive side effects as described above. 

## Is this something you're interested in working on

Yes

**Comment by daimpi** [comment] 2020-11-17 13:50
@jniediek sounds good 👍 

You might also wana check out the tread in #138 which discusses a similar issue and related solution proposals 🙂.

**Comment by alanrick** [comment] 2020-11-17 13:57
> Is the CWA team in contact with their developers for know-how transfer on the pros and cons of the method to be used?

Did anyone find time to contact the UK developers for _Do’s and Dont’s_ based on their experience of this capability in their live app (albeit a different mechanism)?

**Comment by AndreasHGIT** [comment] 2020-12-30 11:54
Think the most of the people discussing this feature are aware of Luca, if not i guess it would be helpful to discuss the concepts, thoughts and so on with that project. https://luca-app.de/

**Comment by Ein-Tim** [comment] 2020-12-30 14:32
@AndreasHGIT 

Thank you for the link, I did not know luca before. 
If I understand correctly, this App still transfers the Data to the Health Authority (not anonymous)...
I think for CWA we should consider an approach without the health authority, since they already now have far too much work and, as already done by the

**Comment by Ein-Tim** [comment] 2020-12-30 14:39
@AndreasHGIT 

Thank you for the link, I did not know _luca_ before. 
If I understand correctly, this App still transfers the Data to the Health Authority (not anonymous)...
I think for CWA we should consider an approach without the health authority, since they already now have far too much work and, as already done by the [UK App](https://github.com/corona-warn-app/cwa-wishlist/issues/138#issuecomment-698275552), it should be possible to introduce this without data transferred to the authority by building this on top of the GAEN-Framework (which also keeps the anonymity of everyone).

**Comment by AndreasHGIT** [comment] 2020-12-30 16:11
Hello Tim,
LUCA I see as a addition to the contact tracing the App does today.

The main use case I would see for Restaurants, Events and so on where today there is the obligation to have paperlists with persons, so that they can be informed if there was a COVID incident. In that case the Health authorities are checking the restaurants papers. 

For sure in must be really discussed if the trust to the App would suffer if there is a additional functionality which requires a registration with personal contact data.

Regards
-- 
Andreas Hezel

**Comment by Ein-Tim** [comment] 2021-04-25 08:52
Hey @medienintegration, version 2.0, which contains the event-registration, has been released on the 21.04.2021 (see blog post "[Project team releases Corona-Warn-App 2.0 with event registration](https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/)"). The releases can be found [here](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.3) for Android and [here](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.0.3) for iOS.
Do you see your proposal fulfilled by this feature? 
If yes, I'd like to ask you if you could close this issue. 

Thank you!

**Comment by heinezen** [comment] 2021-04-25 11:59
Hello everyone,

This feature has been implemented in CWA 2.0 as part of the event registration feature.

This issue will be closed. If you have new ideas for the current implementation of the feature, please consider opening a new issue.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-04-25 11:59 UTC
Labels: approved, event-registration, feature request, mirrored-to-jira

**Comment by medienintegration** [comment] 2021-04-26 14:34
Hallelujah.
