### ISSUE TITLE
Booking of appointments at partners' test centers

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-wishlist#502] opened 2021-05-05 05:48 UTC
## Feature description

After implementing #498, you should also implement that appointments can be booked via the apps.
I think of a map where you can look for the nearest test center and then book an appointment.

## Problem and motivation
Users have first to go to the website to look, which partners do tests and then they have to click through all the (currently 6) websites to look for an appointment near their place of residence.

## Is this something you're interested in working on

No.

**Comment by Ein-Tim** [comment] 2021-05-05 06:04
Is this a duplicate of #398?

**Comment by DerVogel2020** [comment] 2021-05-05 06:23
Closed because of #398.

**Closed** 2021-05-05 06:22 UTC
Labels: feature request
