### ISSUE TITLE
Receive test result from people not using the App

### ISSUE THREAD

**Issue by Hotwheels93** [corona-warn-app/cwa-wishlist#48] opened 2020-06-24 12:07 UTC
As I’m working at ICU in a hospital, I would like to have a feature to submit contacts to positive tested patients who don’t use the app. 
Not only as medical staff, but for all people who don’t use the app, but get tested positive.

--------
Internal Tracking ID: EXPOSUREAPP-2142

**Comment by daimpi** [comment] 2020-06-30 13:28
Could you elaborate a bit on the functionality that you're looking for?
What do you mean by "submitting contacts to positive tested patients who don’t use the app"?

**Comment by Hotwheels93** [comment] 2020-07-01 03:47
> Could you elaborate a bit on the functionality that you're looking for?
> What do you mean by "submitting contacts to positive tested patients who don’t use the app

Yes, of course. Example: We receive a positive test result of a patient who’s got no smartphone. I don’t get testet until I show any symptoms. I‘am using  the app, but my risk will be false low, because the positive tested patients don’t share their results. This affects medical staff all over Germany who treat infectious patients.

**Comment by daimpi** [comment] 2020-07-01 12:47
Thanks for the elaboration. I think I understand better now what you're after :)

Regarding this idea: Even if your patient had a smartphone with the app (and chose to share their positive result) you'd get a warning on your phone that you have been in contact with an infected person which is something you already knew because you were in contact with this patient and know their result. 
The app doesn't have 2nd (or higher) order contact tracing i.e. contacts of those who tested positive cannot be notified unless they get a positive test themselves. This limitation is to a certain degree inherent to the protocol due to its privacy protection/anonymity (see [here](https://github.com/corona-warn-app/cwa-wishlist/issues/24) for more discussion on that topic in particular [this comment](https://github.com/corona-warn-app/cwa-wishlist/issues/24#issuecomment-633275541)). 

The app also cannot notify future contacts (by design): it can only notify those who were in range of your phone **before** you upload your positive test (see [here](https://github.com/corona-warn-app/cwa-documentation/issues/326)). So even if you got a TAN (to confirm you’re infected) the moment you learned your patient is positive, the app would only be able to notify your past contacts and assume you’re self-quarantining. 

How do you as a healthcare provider currently proceed when you’re informed that you were in contact with a positive patient? Are you be able to self-quarantine and get tested in a timely manner? 
As an outsider it sounds worrisome to me that the people working on the front lines can only get tested when they themselves become symptomatic especially considering all the evidence for pre-/asymptomatic spread we have gathered so far. Imo we should have constant screening for people working in high risk settings like an ICU, but at the very least we have to provide fast tests for everyone who requests it and not only when they become symptomatic Oo.

On a more personal note: I would like to thank you very much for the invaluable work you’re doing ❤️.

**Comment by Hotwheels93** [comment] 2020-07-17 14:58
Thank you for your detailed explanation! In case we have contact to a positive tested patient, we are told limit contact between nurse and positive patients, to avoid the risk for the other patients, but we don't get any test in a regular period of time to check if we may be positive as well. Since BGM paused the nurse:patient limitations, we have shifts without the number of necessary staff to fulfill all the needs of the patients, because hospitals are forced to save money..
There were several times I had unspecific symptoms after contact to patients who had respiratory symptoms and in need of ICU care, but in the beginning of corona outbreak it took 2-4 days until test results were available. Even then we were not tested, most of our team members have not been tested yet. Now we receive results faster, but it depends on the kind of test and if the probe is a regular case or if its CITO, which results in more costs. 

Thank you too for your work and support in the Corona-Warn-App, it is great support and a good example of open source software and interdisciplinarity!

**Comment by Ein-Tim** [comment] 2020-12-31 14:15
Maybe we could change the title of this Issue to something like "Receive test result from people not using the App"

**Comment by larswmh** [comment] 2022-06-13 14:01
Closing this issue as its related internal ticket was set to obsolete.

> As the patients, who do not use the app, have not exchanged any random-IDs, this proposal is not possible from a technical point of view.

**Closed by larswmh** 2022-06-13 14:01 UTC
Labels: feature request, mirrored-to-jira
