### ISSUE TITLE
UK (I think?)

### ISSUE THREAD

**Issue by dscheffy** [corona-warn-app/cwa-wishlist#72] opened 2020-06-26 16:45 UTC
My wife wasn't able to install the app on her android phone, I had no problem. I'm not actually sure what country her phone is associated with -- because contrary to popular belief, there's no way to set it. The best you can do is change your "payment country", which as you can see from this google play forum response is only "among" the data points that is used to determine your play store country -- https://support.google.com/googleplay/forum/AAAA8CVOtD8lMUUlNtyhvg/?hl=en&gpf=%23!topic%2Fplay%2FlMUUlNtyhvg
When we lived in the UK, my wife couldn't install the "three" app to manage her mobile phone sim card account. I was able to install it on my phone without any problems (even though I wasn't using three, so it was useless). In order to fix the problem, we added our UK bank account as a payment method -- simply to get google to add her to the UK store. It didn't work though. She still couldn't add the app. I on the other hand have never added a payment method, so my account seems to be unlocked and able to install apps from anywhere. We could try changing her payment over to a german bank account, but since it didn't work when we tried it in the UK, we don't have much confidence that it would fix the issue here either. 
How can we get this message across to the legal department that thinks it would be a problem to open up the app to other countries? Google isn't interested in being liable for determining what country the user is in -- they only care about this for search and marketing purposes. If they think that pushing this liability off onto google is saving them from the liability, they're only opening themselves up to another liability.

**Comment by tkowark** [comment] 2020-06-28 13:44
Thank you for your suggestion. Unfortunately, this is a duplicate of #40

**Closed by tkowark** 2020-06-28 13:44 UTC
Labels: country

**Comment by dscheffy** [comment] 2020-06-28 15:52
Ugh, sorry. I actually searched for UK, but I guess I failed to notice that I was only searching page 1 of 3. I don't even have the UK / GB / England excuse to fall back on... Thanks for consolidating.
