### ISSUE TITLE
More frequent data updates (polling frequency)

### ISSUE THREAD

**Issue by kno10** [corona-warn-app/cwa-wishlist#261] opened 2020-11-08 22:39 UTC
Clearly polling for data updates once a day is not enough in the current situation.
A user that is tested positive will not be able to warn his contacts until the next day when the next round of updates is distributed.

Rather than only updating at around 1-2 in the morning, configure both server and client to update at least 4 times a day.

Consider someone receiving his positive test result at 9 in the morning, sharing the result with the app at 10. This could be distributed to other users with a "lunch" update around 13:00, and the affected users can get tested on the same day.
Currently, they will not be notified until the next day with the 1am morning update.

By now you should have a fairly good statistic on when test results are shared with the app, so you could even choose optimal update times based on this information. Which updates are most likely to allow some high-risk contact to be tested earlier?

**Comment by Ein-Tim** [comment] 2020-11-09 05:41
This is something what already is worked on, please see https://github.com/corona-warn-app/cwa-backlog/issues/2

**Comment by heinezen** [comment] 2020-11-10 12:26
Hello @kno10 ,

Thank you for the suggestion. This is already being addressed by the development team. You can follow the discussion @Ein-Tim linked (https://github.com/corona-warn-app/cwa-backlog/issues/2) for the latest updates on the development. I will close tthis issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-11-10 12:26
Duplicate of https://github.com/corona-warn-app/cwa-backlog/issues/2

**Closed by heinezen** 2020-11-10 12:26 UTC
Labels: enhancement
