### ISSUE TITLE
Negativer Corona-Test, Status weiterhin rot

### ISSUE THREAD

**Issue by Oaky78** [corona-warn-app/cwa-wishlist#242] opened 2020-10-29 09:39 UTC
1. App Status rot, wegen mehrerer Risikobegegnungen. 
2. Test mit QR Code eingescannt 
3. Negatives Testergebnis erhalten

IST: App Status weiterhin rot, auch nach Aktualisierung am nächsten Tag (Siege Screenshot)

![3D25465F-FF71-415D-941E-5E854056CC2F](https://user-images.githubusercontent.com/20914123/97551195-f473fa00-19d2-11eb-95d0-baccd20265f3.png)

SOLL: App sollte bei negativem Ergebnis wieder grün werden.

## Technical details
- CWA version 1.5.2
- iOS Version: 13.7
- Device: iPhone 8

**Comment by heinezen** [comment] 2020-10-29 15:58
Hello everyone,

I agre that this issue is not really a bug, but rather a missing feature. Therefore, we have created a Jira ticket (EXPOSUREAPP-3496) for the associated feature request in https://github.com/corona-warn-app/cwa-wishlist/issues/239. The thread here and the thread in https://github.com/corona-warn-app/cwa-wishlist/issues/239 have been integrated into the Jira ticket, so the discussion is not lost.

I will close this issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/239, so please continue the discussion there. This was done to better monitor the discussion from our side.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-29 15:58
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/239

**Closed by heinezen** 2020-10-29 15:58 UTC
