### ISSUE TITLE
Erinnerung an einen Tagebuch-Eintrag

### ISSUE THREAD

**Issue by 9ce59b18** [corona-warn-app/cwa-wishlist#786] opened 2022-02-12 17:20 UTC

**Comment by Ein-Tim** [comment] 2022-02-12 17:43
Hey @Blausteinstaub 👋

This seems like a duplicate of #294 to me, what do you think?

**Comment by 9ce59b18** [comment] 2022-02-12 18:02
Oh... Yes, Sorry

**Closed as completed** 2022-02-12 18:02 UTC
Labels: duplicate, feature request
