### ISSUE TITLE
Implementation of the possibility to transfer the vaccination certificate into the Apple Wallet app.

### ISSUE THREAD

**Issue by DrDosenbier** [corona-warn-app/cwa-wishlist#562] opened 2021-06-22 09:45 UTC
Currently, it is only possible to save the vaccination certificate in the CWA app and the CovPass app. The possibility to transfer the certificate to Apples own wallet app would be desirable.  

Regarding privacy concerns, I am aware. Double-clicking the iPhone's side button brings up Wallet directly from the lock screen, without verification through FaceID or TouchID. However, it is always possible to disable this option in the settings.
Consequently, transferring the certificate would be at your own risk.

Advantages that would arise: Faster viewing of the vaccination certificate as well as past test results.

Disadvantages that would arise: Easier viewing of personal data by third parties.

First time GitHub user here...I will gladly accept tips or suggestions regarding my post!

**Comment by jucktnich** [comment] 2021-06-22 09:47
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/2965 It got declined.

**Comment by heinezen** [comment] 2021-06-23 04:14
Hello @DrDosenbier ,

Thank you for your request. Your feature request was already made by someone else in https://github.com/corona-warn-app/cwa-app-ios/issues/2965. The feature has been declined by the dev team and our stakeholders and the thread has been closed, but you can still comment there if you think there's something missing in the discussion.

I'll close your issue as a duplicate.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-23 04:14
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/2965

**Closed as completed by heinezen** 2021-06-23 04:14 UTC
Labels: feature request
