### ISSUE TITLE
Name releases to the AppStore consistent

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#452] opened 2021-04-15 12:19 UTC
## Current Implementation

The final release often have numbers like 1.15.1 or 1.14.3, even if it's the first version, wich schould mean it's .0.

## Suggested Enhancement

Name the releases in a consistent way.

## Expected Benefits

Some (older) people get confused by every small inconsistency, and think, that there device has a bug. I don't know, why they are named so inconsistent, but if it's not hard to change it, i would prefer changing it to consisting numbers.

**Comment by Ein-Tim** [comment] 2021-04-15 12:28
I think this inconsistency is caused by the following:

If the version (for example version 2.0) is submitted to the App Store for review & the App Store review team finds bugs, etc. or the development team finds bugs they have to bump the version to a .minor (for example 2.0.1) version when they fix the bug. 
If then in the next review round another mistakes comes up they have to increase the version number again (to for example version 2.0.2).

I hardly believe that anyone gets confused by this, since other apps (take a look at WhatsApp) sometimes even have .patch versions up to 90 or higher.

The versioning of CWA is also explained here: https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-versioning.md

**Comment by jucktnich** [comment] 2021-04-15 12:50
The differnce between WhatsApp is, I think, that at WhatsApp it's obvious, that the logic there is not to just increment one part of the number.

**Comment by Ein-Tim** [comment] 2021-04-15 12:53
@jucktnich 

Yeah, idk, maybe WhatsApp wasn't the best example 😀
But so or so I think this is really nothing that could be changed for the reasons I explained above (but if you want to release a version with known bugs because you don't want to fix them because you want a "clean" version number 😉)

**Comment by jucktnich** [comment] 2021-04-15 12:56
I don't think that's better, I just thought if there was no reason, it would be worth it to change (I know people wich got confused, but better a clean version and confused people as vice versa)

**Comment by Ein-Tim** [comment] 2021-04-15 13:13
Totally agree with you that this should be avoided if there's no reason @jucktnich!

If you consider this as technically not feasible I suggest to close this issue.

**Closed** 2021-04-15 13:19 UTC
Labels: enhancement
