### ISSUE TITLE
Make check-in and check-out more intuitive

### ISSUE THREAD

**Issue by Smponi** [corona-warn-app/cwa-wishlist#533] opened 2021-05-26 19:55 UTC
## Current Implementation

On android to scan a QR-Code for check-in you have to:
1. open the app
2. Go to Check-in
3. Click __QR-CODE SCANNEN__
4. Scan it   

So you have to do 3 clicks every time just to scan the QR-Code.
Same for the check out. You have to open the app, go to check-in and then you can check-out.

## Suggested Enhancement

I would like to suggest a short-cut for the check-in and check-out system.   
So my idea for the **check-in** are the following:
1. Include a widget which opens directly the QR-Scanner for the check-in.
2. When the QR-Code is scanned with the native camera app, open it directly in the app. For me it showed an URL and I couldn't open it in the app. (Tested on a Pixel 3a)

For **check-out** I would suggest a pinned notification. This Notification has some information and a "Jetzt auschecken" Button. 
So you can directly check-out with only one click. And this notification only disappears, if you checked-out,

## Expected Benefits

- Fewer clicks
- You see if you haven't checked-out after leaving

**Comment by Ein-Tim** [comment] 2021-05-26 20:54
Please note that you can long press the Corona-Warn-App app icon and select "Check in" to get directly to the "My check ins" screen.

**Comment by Smponi** [comment] 2021-05-26 21:40
Are you sure? When I long press I can only add something to my diary.
![photo5294013359936615645](https://user-images.githubusercontent.com/17931603/119734750-b4e39280-be7b-11eb-9853-d44ac0773789.jpg)

**Comment by Ein-Tim** [comment] 2021-05-26 21:43
I'm under iOS and there I see this: 
<img src="https://user-images.githubusercontent.com/67682506/119735056-14da3900-be7c-11eb-814e-f68b5ca31ce3.PNG" width="300">

And now I remember, this is not yet implemented under Android, sorry. See: https://github.com/corona-warn-app/cwa-app-android/issues/2858

**Comment by fynngodau** [comment] 2021-05-28 15:41
> When the QR-Code is scanned with the native camera app, open it directly in the app. For me it showed an URL and I couldn't open it in the app. (Tested on a Pixel 3a)

This should also work already. The app registers itself as being able to open e.coronawarn.app links, e.g. here: https://github.com/corona-warn-app/cwa-app-android/blob/9ec222a431340917834e831cc60edd14fa062d27/Corona-Warn-App/src/main/AndroidManifest.xml#L86

**Comment by heinezen** [comment] 2021-06-08 14:46
Hey @Smponi ,

The widget is already implemented on iOS. Android has its own feature request issue here: https://github.com/corona-warn-app/cwa-app-android/issues/2858

> When the QR-Code is scanned with the native camera app, open it directly in the app. For me it showed an URL and I couldn't open it in the app. (Tested on a Pixel 3a)

This is likely a bug. You should be redirected to the CWA if you scan the code with the native camera or another QR code app. Please report it in the https://github.com/corona-warn-app/cwa-app-android/ repository. Thank you

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-17 13:51
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/2858

**Closed by heinezen** 2021-06-17 13:51 UTC
Labels: enhancement
