### ISSUE TITLE
Differentiate Test- and Vaccination Certificate not only by shade of blue

### ISSUE THREAD

**Issue by PatrickPaetzold** [corona-warn-app/cwa-wishlist#606] opened 2021-08-02 15:18 UTC
## Current Implementation
If a vaccination certificate and a COVID Test certificate are registered in the CWA, they look nearly identical. Only the shade of blue differentiates them. However, it is not immediately obvious and requires a click on the certificate to tell them apart certainly. In the image, the minute difference in color can be seen. 
<img src="https://user-images.githubusercontent.com/18719951/127881684-2b4bb213-c0ef-4ad6-8245-bfa66d898499.jpg" height="500">

## Suggested Enhancement
Change "Digitales COVID-Zertifikat der EU" to something like "Digitales COVID-Schnelltestzertifikat der EU" for COVIS tests and "Digitales COVID-Zertifikat der EU" to "Digitales COVID-Impfzertifikat der EU", similar how it is presented in the CovPass app.

## Expected Benefits
The users can immediately tell the vaccination and the test certificate apart.

---
Internal Tracking ID: [EXPOSUREAPP-8821](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8821)

**Comment by dsarkar** [comment] 2021-08-03 10:38
Hi @PatrickPaetzold,

Thanks for the suggestion. This is forwarded internally. Any news on this will be published here.

---
Internal Tracking ID: [EXPOSUREAPP-8821](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8821)
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment] 2021-08-15 13:29
The logic seems to be that the topmost person is displayed in a lighter shade of blue. The first person may be the one that is selected as "device owner", but if no person is selected as such, this is not the case.

I think a better color-code would be to change the color according to the type of certificate that is displayed for the person. However, we need to consider that this leaks this information to the verifier (the person) even if they take measures like using CovPass Check to avoid telling apart vaccinated and tested persons.

**Comment by larswmh** [comment] 2022-06-15 08:02
Closing this issue as the related internal ticket is set to `obsolete`.

This is working as designed. 

Developer comment:

> It must be clear to everyone, that checking the validity of a certificate (independent of the color) only works with the CovPass Check App and checking the identity of the person.
> So it would be contraproductive to use different colors, because the persons, who must check the validity will tend to only look at the colors of the certificate.

**Closed as not planned by larswmh** 2022-06-15 08:02 UTC
Labels: enhancement, mirrored-to-jira, certificates
